### ISSUE TITLE
The macro plays only once

### ISSUE THREAD

**Issue by leytondsilva** [Zuzu-Typ/Input-Recorder#2]
The play once is unchecked and it just wont repeat.
I enter the name of the macro, click add, after recording it I hit escape and then when running it just runs once. I am probably doing something wrong.

I really like this repository and the work you and others have put in : )

Thanks!!

**Comment by Zuzu-Typ** [comment]
Hello there Leyton,

I'm honestly surprised that there are people out there using this software.
I originally made it for a viewer of my (now abandoned) YouTube channel and found it to be useful for me as well.
I introduced the _Play Once_ feature to enable the possibility of sharing e.g. passwords for one time logins.

The way it is currently implemented is per set of macros. This means, if you save a set of macros with the _Play Once_ option set, it will only allow every single one of them to be played back once.

Also it's more of a "open once" kind of deal, as you can't open it again if you decide to close it once opened.

There's even a very easy workaround to open a file again, since I didn't have a particularly untrustworthy or desperate audience in mind when designing it.


Anyway, the entire thing could use some work.
Unfortunately so do my other libraries.
I'm currently focussing my work on [PyGLM](https://github.com/Zuzu-Typ/PyGLM) (which desperately needs documentation) and a not yet published little piece of software.

Either way, I will definitely come back to ```Input-Recorder``` in the future, so please feel free to request more features you would like to see.

Cheers
--Zuzu_Typ--

**Comment by leytondsilva** [comment]
Thanks for the quick reply, well now I understood the functionality of the play once.
I'll try to implement a loop macro function.
I'll surely check out your other repositories : )
